// src/lib/components/global/Branding.svelte
<script>
import { base } from "$app/paths";
import Logo from "$visuals/Logo.svelte";
</script>

<section role="banner">
	<a class="flex gap-3 items-center" href={base}>
		<Logo classes="relative top-[1px] size-10 fill-primary-200"/>
		<h1 class="font-medium text-2xl text-primary-50">Mikrouli</h1>
	</a>
</section>

// apps/website/src/components/branding/branding.tsx
import { component$, useStylesScoped$ } from '@builder.io/qwik';
import { FaLeafSolid } from '@qwikest/icons/font-awesome';

import styles from './branding.css?inline';

export const Branding = component$(() => {
  useStylesScoped$(styles);

  return (
    <>
      <a href="/" class="flex gap-2 items-center text-green-600">
        <FaLeafSolid class="w-8 h-8" />
        <h1 class="text-2xl font-medium">Mikrouli</h1>
      </a>
    </>
  );
});
